### ISSUE TITLE
Additional configurations

### ISSUE THREAD

**Issue by stefan-cooper** [stefan-cooper/SpigotUHC#11]
## Discussion/Proposal

Was chatting with Shurf and we talked about some other fun configurations we could add.

- [x] When players are killed, they drop (or have a chance to drop?) their player head which when put into a crafting bench will craft a golden apple `player.head.golden.apple=boolean` https://github.com/stefan-cooper/SpigotUHC/pull/20
- [x] Show current size of the world border in the boss bar `world.border.in.bossbar=boolean` https://github.com/stefan-cooper/SpigotUHC/pull/28
- [ ] Show top killers in sidebar `killers.in.scoreboard=boolean`
- [ ] Create a `timestamps.txt` that we update with timestamps of notable events (kills) `enable.timestamps=boolean`
- [ ] Enable death chat. Alive players cannot see dead players chat `death.chat=true`

**Comment by JawadJ** [comment]
https://www.spigotmc.org/threads/playerdeathevent-not-triggering.549283/ getting heads

**Comment by stefan-cooper** [comment]
New issues raised for the additional configurations:

#38
#39 
#40
