### ISSUE TITLE
Allow revival of a teammate  

### ISSUE THREAD

**Issue by BenParsley** [stefan-cooper/SpigotUHC#41]
Perhaps you have to trade x amount of a certain resource, or maybe if you take their player head to a certain location you can revive them.

**Comment by stefan-cooper** [comment]
Starter for 10:

After a player has died and their head has been dropped. If their teammates pick up the head and take it to a specific (config-defined) location and stay in the location for a set (config-defined) amount of time, that teammate will respawn.

Additional bits:

- The head is remvoved from the inventory after the revive
- If you step outside of the revive location, the revive is cancelled.
- If the head leaves the inventory during the revival, the revive is cancelled
- When the revive process begins, an alert is sent in chat that someone is being revived.

Questions:

- Should this be available for the full game, or just for the first set amount of time?
- How much health should the revived player spawn with?

Config values:

`revive.time`=<number>`
`revive.location.size=<number>`
`revive.location.x=<number>`
`revive.location.z=<number>`
`revive.health=<number>`

@BenParsley @JawadJ @shurfey wdyt?
